[package]
edition = "2018"
name = "rust-parse"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jemallocator = {version = "0.3.2", optional = true}
lib-ruby-parser = "4.0.1+ruby-3.1.1"

[profile.release]
lto = true
